name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

#      - name: rsync deployments
#        uses: burnett01/rsync-deployments@4.1
#        with:
#          # 这里是 rsync 的参数 switches: -avzh --delete --exclude="" --include="" --filter=""
#          switches: -avzh
#          path: /
#          remote_path: /www/wwwroot/action.ll2.ink
#          remote_host: ll2.ink
#          remote_port: 1997
#          remote_user: root
#          #        remote_password: q
#          remote_key: ${{ secrets.MY_UBUNTU_RSA_PRIVATE_KEY }}
      - name: set ssh key # 临时设置 ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.MY_UBUNTU_RSA_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
#          ssh-keyscan ${{secrets.HOST}} >> ~/.ssh/known_hosts

      - name: deploy
        run: |
          ssh -p 1997 root@${{secrets.HOST}} "
              cd /root/action; # 事先 git clone ** server 分支**
              git pull ; # 清空所有改动
              cp -r ./view/* /www/wwwroot/action.ll2.ink ;
          "

#      - name: Deploy to Server
#        uses: easingthemes/ssh-deploy@v2.0.8
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.MY_UBUNTU_RSA_PRIVATE_KEY }}
#          ARGS: "-avz --delete"
#          REMOTE_HOST: ${{ secrets.HOST }}
#          REMOTE_USER: ${{ secrets.USERNAME }}
#          REMOTE_PASSWORD: 'q'
#          REMOTE_PORT: ${{ secrets.PORT }}
#          SOURCE: "/view"
#          TARGET: "/www/wwwroot/action.ll2.ink"
