name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    -   name: Deploy to Server
          uses: easingthemes/ssh-deploy@v2.0.8
          env:
            SSH_PRIVATE_KEY: ${{ secrets.MY_UBUNTU_RSA_PRIVATE_KEY }}
            ARGS: "-avz --delete"
            REMOTE_HOST: ${{ secrets.HOST }}
            REMOTE_USER: ${{ secrets.USERNAME }}
            REMOTE_PORT: ${{ secrets.PORT }}
            SOURCE: "/"
            TARGET: "/www/wwwroot/action.ll2.ink"
